[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Isaac Imitation Learning"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description="Imitation learning extension for Isaac Lab (ACT, Diffusion Policy, BC-RNN)"
repository = "https://github.com/isaac-sim/IsaacLab.git"
keywords = ["imitation-learning", "robomimic", "isaaclab", "act", "diffusion-policy"]

[dependencies]
"isaaclab" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "isaac_imitation_learning"
